// combined/react-script.js
import {viewDelay, wait, getTodoList} from './common-script.js';
import React from 'https://esm.sh/react@18/?dev';
import ReactDOM from 'https://esm.sh/react-dom@18/client?dev';

// Define a component called Greetings
function Greetings() {
    wait(viewDelay);

    const [isLoading, setIsLoading] = React.useState(true);
    const [todoList, setTodoList] = React.useState([]);

    React.useEffect(() => {
        async function fetchTodoList() {
            const list = await getTodoList();
            setTodoList(list);
            setIsLoading(false);
        }
        fetchTodoList();
    }, []);

    return <div>
        <h1>Todo List</h1>
        <ul>
            {isLoading ? <p>Loading...</p> : todoList.map((item, index) => {
                return <li key={index}>{item.title}</li>
            })}
        </ul>
        <p>It is now {new Date().toLocaleString()}</p>
    </div>;
}

ReactDOM.createRoot(document.getElementById("react-content"))
    .render(<Greetings/>);

// combined/lit-script.js
import {html, LitElement} from 'https://cdn.jsdelivr.net/gh/lit/dist@3/all/lit-all.min.js';
import {Task} from 'https://cdn.jsdelivr.net/npm/@lit/task@1.0.1/+esm';
import {getTodoList, viewDelay, wait} from './common-script.js';

export class MyElement extends LitElement {
    static properties = {
        version: {},
        time: {},
    };

    constructor() {
        super();
        this.time = new Date().toLocaleString();
    }

    _productList = new Task(this, {
        task: async () => {
            wait(viewDelay)
            return await getTodoList();
        },
        args: () => [this.time]
    })

    render() {
        wait(viewDelay)
        return html`
            <h1>Todo List</h1>
            <ul>
                ${this._productList.render({
                    pending: () => html`<p>Loading...</p>`,
                    complete: (todoList) => todoList.map(item => html`
                        <li>${item.title}</li>`)
                    ,
                    error: (error) => html`<p>Error: ${error}</p>`
                })}
            </ul>
            <p>It is now ${this.time}</p>
        `
    }
}

customElements.define('my-element', MyElement);
